[build-system]
requires = [
    "setuptools>=61",
    'tomli; python_version < "3.11"',
]
build-backend = "setuptools.build_meta"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "snakemake/_version.py"
versionfile_build = "snakemake/_version.py"
tag_prefix = "v"
